server.port=3001
spring.datasource.url=jdbc:postgresql://localhost:5433/kampuskart
spring.datasource.username=erick-lamboe
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=KampusKartSecretKey2026ForJWTTokenGenerationAndValidation
jwt.expiration=604800000
